import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./navBar";
import AuthProvider from "./auth/Provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen  flex flex-col`}
      >
        <AuthProvider>
          <NavBar />
          <main className="flex flex-1 w-full">
            <aside className="bg-slate-500 h-full w-78 pt-5 pl-20 shadow-[1px_5px_10px_rgba(0,0,0,0.25)] ">
              Sidebar
            </aside>
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
